/* Shared geometry, materials and static batching. No external assets or fetch. */
window.Forest = {};
(() => {
const F=window.Forest,T=window.THREE;F.T=T;F.V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
F.geo={sphere:new T.SphereGeometry(1,14,10),box:new T.BoxGeometry(1,1,1),cone:new T.ConeGeometry(1,1,10),cylinder:new T.CylinderGeometry(1,1,1,10),leaf:new T.SphereGeometry(1,8,6),torus:new T.TorusGeometry(1,.12,6,20)};
const mats=new Map();F.mat=(c)=>{if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.9}));return mats.get(c)};
F.part=(parent,type,color,x,y,z,sx=1,sy=sx,sz=sx,rx=0,ry=0,rz=0)=>{const m=new T.Mesh(F.geo[type],typeof color==='string'?F.mat(color):color);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.rotation.set(rx,ry,rz);parent.add(m);return m;};
F.group=(parent,x=0,y=0,z=0)=>{const g=new T.Group();g.position.set(x,y,z);parent.add(g);return g;};
F.rod=(p,c,a,b,r)=>{const v=F.V(...a),w=F.V(...b),o=F.part(p,'cylinder',c,0,0,0,r,v.distanceTo(w),r);o.position.copy(v).add(w).multiplyScalar(.5);o.quaternion.setFromUnitVectors(F.V(0,1,0),w.sub(v).normalize());return o};
// Merge rigid meshes by material; animated joints remain independent groups.
F.mergeRigid=(group)=>{group.updateMatrixWorld(true);const inverse=group.matrixWorld.clone().invert(),buckets=new Map(),remove=[];group.traverse(m=>{if(!m.isMesh||m.isInstancedMesh)return;const key=m.material.uuid;if(!buckets.has(key))buckets.set(key,{mat:m.material,geos:[]});const g=m.geometry.clone().applyMatrix4(new T.Matrix4().multiplyMatrices(inverse,m.matrixWorld)).toNonIndexed();buckets.get(key).geos.push(g);remove.push(m)});for(const m of remove)m.removeFromParent();for(const b of buckets.values()){let p=[],n=[],uv=[];for(const g of b.geos){p.push(...g.attributes.position.array);n.push(...g.attributes.normal.array);uv.push(...(g.attributes.uv?g.attributes.uv.array:new Float32Array(g.attributes.position.count*2)));g.dispose()}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('normal',new T.Float32BufferAttribute(n,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeBoundingSphere();group.add(new T.Mesh(g,b.mat));}};
F.batches=new Map();const dummy=new T.Object3D();F.stamp=(type,color,x,y,z,sx=1,sy=sx,sz=sx,rx=0,ry=0,rz=0)=>{let key=type+color;if(!F.batches.has(key))F.batches.set(key,{type,color,matrices:[]});dummy.position.set(x,y,z);dummy.rotation.set(rx,ry,rz);dummy.scale.set(sx,sy,sz);dummy.updateMatrix();F.batches.get(key).matrices.push(dummy.matrix.clone());};
F.flush=(scene)=>{for(const b of F.batches.values()){const o=new T.InstancedMesh(F.geo[b.type],F.mat(b.color),b.matrices.length);b.matrices.forEach((m,i)=>o.setMatrixAt(i,m));o.computeBoundingSphere();scene.add(o)}F.batches.clear();};
let seed=4707;F.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
F.label=(parent,text,x,y,z,width=4,bg='#fff8dd',fg='#334d37')=>{const c=document.createElement('canvas');c.width=1024;c.height=256;const q=c.getContext('2d');q.fillStyle=bg;q.fillRect(0,0,1024,256);q.strokeStyle='#ba9762';q.lineWidth=12;q.strokeRect(8,8,1008,240);q.font='bold 85px sans-serif';q.textAlign='center';q.textBaseline='middle';q.fillStyle=fg;q.fillText(text,512,132,950);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(width,width/4),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));m.position.set(x,y,z);parent.add(m);return m;};
})();
