(() => {
const F=Forest,T=THREE,$=id=>document.getElementById(id);
function fail(e){$('loading').classList.add('done');$('error').hidden=false;$('error').textContent='ワールドを開けませんでした。'+e.message+'。WebGL 2対応のChrome / Safariで、フォルダ全体を展開して開いてください。';console.error(e);}
try{
const scene=new T.Scene();scene.background=new T.Color('#c8dfd5');scene.fog=new T.Fog('#c8dfd5',40,105);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;$('game').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','ワールド画面：ドラッグでカメラ回転');renderer.domElement.tabIndex=0;
scene.add(new T.HemisphereLight('#fff8e2','#789f68',2.2));const sun=new T.DirectionalLight('#fff1d4',2.8);sun.position.set(-18,30,20);scene.add(sun);
const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,160),player=F.V(-17,0,12),target=F.V(),desired=F.V(),direction=F.V(),world=F.makeWorld(scene),residents=F.makeResidents(scene);
// Soft contact discs rather than expensive realtime shadow maps.
const shadowGeo=new T.CircleGeometry(1,24),shadowMat=new T.MeshBasicMaterial({color:'#46623c',transparent:true,opacity:.17,depthWrite:false});shadowGeo.rotateX(-Math.PI/2);
for(const n of residents){const s=new T.Mesh(shadowGeo,shadowMat);s.position.set(n.x,.02,n.z);s.scale.set(.58,1,.43);scene.add(s);}
const marker=new T.Group();scene.add(marker);F.part(marker,'sphere','#efd99a',0,.22,0,.2,.18,.2);F.part(marker,'leaf','#cfad51',-.1,.47,0,.1,.27,.055,0,0,-.5);F.part(marker,'leaf','#7fa36b',.11,.47,.015,.095,.22,.05,0,0,.6);
const ring=F.part(marker,'torus','#f5e7bc',0,.025,0,.35,.35,.11,Math.PI/2);
const controls=F.makeControls(renderer.domElement,player,world),dialogue=F.makeDialogue(residents,player,camera);
const map=$('minimap').getContext('2d');function minimap(){const q=map,u=x=>160+x*2.85,v=z=>160+z*2.85;q.clearRect(0,0,320,320);q.fillStyle='#e1e8c7';q.beginPath();q.rect(0,0,320,320);q.fill();q.fillStyle='#b8d09f';q.fillRect(15,15,290,125);q.fillStyle='#8cc8c5';q.beginPath();q.ellipse(u(25),v(-38),13*2.85,10*2.85,0,0,Math.PI*2);q.fill();q.lineCap='round';q.strokeStyle='#f8e7bb';q.lineWidth=11;for(const p of world.paths){q.beginPath();q.moveTo(u(p[0]),v(p[1]));q.lineTo(u(p[2]),v(p[3]));q.stroke();}q.fillStyle='#b97c59';q.fillRect(u(-27),v(-7),16*2.85,10*2.85);q.fillStyle='#c3a170';for(const p of world.plots)q.fillRect(u(p.x-5),v(p.z-3.5),28,20);q.font='19px sans-serif';q.textAlign='center';q.fillStyle='#4c6451';q.fillText('学校',u(-20),v(1));q.fillText('農園',u(24),v(30));q.fillText('森',u(-24),v(-35));q.fillText('湖',u(26),v(-38)+6);
for(const n of residents){q.fillStyle='#677e59';q.beginPath();q.arc(u(n.x),v(n.z),3.5,0,Math.PI*2);q.fill();}q.fillStyle='#cf9134';q.strokeStyle='#fffef5';q.lineWidth=3;q.beginPath();q.arc(u(player.x),v(player.z),6,0,Math.PI*2);q.fill();q.stroke();const yaw=controls.getCamera().yaw;q.beginPath();q.moveTo(u(player.x)-Math.sin(yaw)*10,v(player.z)-Math.cos(yaw)*10);q.lineTo(u(player.x)-Math.sin(yaw+.45)*17,v(player.z)-Math.cos(yaw+.45)*17);q.lineTo(u(player.x)-Math.sin(yaw-.45)*17,v(player.z)-Math.cos(yaw-.45)*17);q.closePath();q.fill();}
for(const n of residents){const row=document.createElement('div');row.className='resident-row';row.dataset.resident=n.id;const dot=document.createElement('span');dot.className='dot';dot.textContent='❧';const name=document.createElement('span');name.textContent=n.name;const area=document.createElement('small');area.textContent=n.area;row.append(dot,name,area);$('resident-list').appendChild(row);}
let paused=false,modalCount=0;function setPaused(){controls.setPaused(paused||modalCount>0);$('pause').textContent=paused?'散歩を再開':'一時停止';}
$('pause').onclick=()=>{paused=!paused;setPaused()};$('home').onclick=()=>{controls.reset();};$('talk').onclick=()=>dialogue.again();$('camera-left').onclick=()=>controls.rotate(.35);$('camera-right').onclick=()=>controls.rotate(-.35);
for(const id of ['help','residents']){const d=$(id);$(id+'-open').onclick=()=>{modalCount++;setPaused();d.showModal()};d.addEventListener('close',()=>{modalCount=Math.max(0,modalCount-1);setPaused();renderer.domElement.focus()});d.querySelectorAll('.close,.close-help').forEach(b=>b.onclick=()=>d.close());}
$('quality').onchange=()=>{renderer.setPixelRatio($('quality').value==='light'?1:Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight)};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fail(new Error('描画が中断されました。再読み込みしてください'))});
// Optional, visible QA controls for checking each resident without changing normal play.
let diagnostics=null;const inspect=new URLSearchParams(location.search).has('inspect');if(inspect){const panel=document.createElement('section');panel.id='inspection';panel.style.cssText='position:absolute;left:12px;top:190px;max-width:360px;background:#fffbedee;padding:12px;border-radius:12px;z-index:7;font:12px sans-serif';const title=document.createElement('strong');title.textContent='品質確認モード';panel.append(title);diagnostics=document.createElement('pre');diagnostics.id='diagnostics';diagnostics.style.whiteSpace='pre-wrap';panel.append(diagnostics);for(const n of residents){const b=document.createElement('button');b.textContent=n.name+'の前へ';b.style.cssText='font-size:11px;margin:2px;padding:5px';b.onclick=()=>{controls.reset();player.set(n.x,world.groundHeight(n.x,n.z+2.8),n.z+2.8);};panel.append(b);}const b=document.createElement('button');b.textContent='離れる';b.onclick=()=>{player.z+=7;};panel.append(b);document.body.append(panel);}
const box=new T.Box3(F.V(-27.7,0,-7.3),F.V(-10.3,8.2,3.6)),ray=new T.Ray(),hit=F.V();let initialized=false,last=performance.now(),elapsed=0,frame=0,fps=60,errors=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(document.hidden)return;try{
if(!controls.paused){elapsed+=dt;controls.move(dt);F.animateResidents(residents,elapsed,player);world.update(elapsed);}
marker.position.copy(player);marker.children[0].position.y=.24+Math.sin(elapsed*3)*.04;ring.rotation.z=elapsed*.25;
const c=controls.getCamera();target.copy(player).add(F.V(0,1.45,0));desired.set(player.x+Math.sin(c.yaw)*Math.cos(c.pitch)*c.distance,player.y+1.4+Math.sin(c.pitch)*c.distance,player.z+Math.cos(c.yaw)*Math.cos(c.pitch)*c.distance);
direction.copy(desired).sub(target).normalize();ray.set(target,direction);if(ray.intersectBox(box,hit)&&hit.distanceTo(target)<desired.distanceTo(target))desired.copy(target).addScaledVector(direction,Math.max(2.5,hit.distanceTo(target)-.6));
if(!initialized){camera.position.copy(desired);initialized=true;}else camera.position.lerp(desired,1-Math.exp(-dt*9));camera.lookAt(target);dialogue.update();renderer.render(scene,camera);
frame++;fps=fps*.97+(1/Math.max(.001,dt))*.03;if(frame%8===0){$('zone').textContent=world.zone(player.x,player.z);minimap();if(diagnostics)diagnostics.textContent=`住人 ${residents.length}/9 ｜ ${Math.round(fps)} fps\n描画 ${renderer.info.render.calls} calls / ${renderer.info.render.triangles} tris\n位置 ${player.x.toFixed(1)}, ${player.z.toFixed(1)}\n会話 ${dialogue.getState().active||'なし'}\n仔馬：前脚2本 / 後脚2本`;}if(frame===2)$('loading').classList.add('done');
}catch(e){if(!errors++){fail(e);}}}
minimap();requestAnimationFrame(animate);
}catch(e){fail(e)}
})();
